### ISSUE TITLE
Error: code-32000 message

### ISSUE THREAD

**Issue by kolibril13** [rgbkrk/denotebooks#1]
hi @rgbkrk,

just tried this notebook:
https://github.com/rgbkrk/denotebooks/blob/main/Polar%20DataFrames.ipynb

got this:

<img width="940" alt="image" src="https://github.com/rgbkrk/denotebooks/assets/44469195/f2e738cc-f083-4ba9-b542-697156fcfbcf">

any ideas why?

**Comment by kolibril13** [comment]
ok, when I wait 5 seconds before running the second cell, I get this message instead:
<img width="1232" alt="image" src="https://github.com/rgbkrk/denotebooks/assets/44469195/e294448a-4194-4fe0-a449-e6953417a443">

**Comment by rgbkrk** [comment]
Sadly "Promise was collected" is a known issue happening somewhere between v8 and the repl. https://github.com/denoland/deno/issues/20528

The cell likely ran fine but it's pretty annoying to have to rerun to see results.

**Comment by kolibril13** [comment]
thanks for pointing me there!

> The cell likely ran fine but it's pretty annoying to have to rerun to see results.

Thanks for this suggestion, but also with re-running the cell (also after waiting some time) I was not able to reproduce the example from your notebook https://github.com/rgbkrk/denotebooks/blob/main/Polar%20DataFrames.ipynb
instead I get this error in the console:
<img width="588" alt="image" src="https://github.com/rgbkrk/denotebooks/assets/44469195/267492ee-4767-4806-af68-c35aa2fe2c6f">
```console

renderers.js:2 TypeError: Cannot read properties of undefined (reading '__esModule')
    at defaultResolveComponent (renderers.js:2:144767)
    at b (renderers.js:2:141159)
    at renderers.js:2:143518
renderers.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__esModule')
    at defaultResolveComponent (renderers.js:2:144767)
    at b (renderers.js:2:141159)
    at renderers.js:2:143518
﻿
```

**Comment by rgbkrk** [comment]
I see why this is working in Jupyterlab but not VS Code. If you switch the presentation mode to using `text/html` instead it will show up.

<img width="1054" alt="image" src="https://github.com/rgbkrk/denotebooks/assets/836375/e8f9c328-77cf-4aea-a90d-798374da779d">

It appears that their handling for the data resource payload isn't rendering properly but the HTML one is.

By the way I just updated the notebooks to use the most recent version of `display`. Here's the sample code:

```typescript
import pl from "npm:nodejs-polars";
import { display } from "https://deno.land/x/display@v1.0.1/mod.ts";

let response = await fetch(
  "https://cdn.jsdelivr.net/npm/world-atlas@1/world/110m.tsv",
);
let data = await response.text();
let df = pl.readCSV(data, { sep: "\t" });
await display(df)
```

cc @donjayamanne

**Comment by kolibril13** [comment]
Changing the presentation mode in VS Code worked, thanks for the hint!

**Comment by DonJayamanne** [comment]
Sorry I never got back on this
Found that it’s just not working, looks like this mine type was added and  hasn’t worked for a while

**Comment by rgbkrk** [comment]
It's a great media type if you want a scrollable grid for a table instead of a static HTML view. While we could fix the original renderer it would be really cool if Microsoft/VS Code folks had their own implementation of a grid. 

The schema is https://specs.frictionlessdata.io/schemas/tabular-data-resource.json

In pandas you can enable it with:

```python
pd.set_option("display.html.table_schema", True)
```

and then just type `df` in cells.

For an example of the format, try this:

```python
import pandas as pd

df = pd.read_csv(
    "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv"
)
# Enable { schema, data } output as JSON
pd.set_option("display.html.table_schema", True)

# Now to demonstrate what's inside
import json

ip = get_ipython()

# Enable { schema, data } output as JSON
pd.set_option("display.html.table_schema", True)
data, metadata = ip.display_formatter.format(df.head(5))

data_resource = data['application/vnd.dataresource+json']

print(json.dumps(data_resource, indent=2))
```

```json
{
  "schema": {
    "fields": [
      {
        "name": "index",
        "type": "integer"
      },
      {
        "name": "species",
        "type": "string"
      },
      {
        "name": "island",
        "type": "string"
      },
      {
        "name": "bill_length_mm",
        "type": "number"
      },
      {
        "name": "bill_depth_mm",
        "type": "number"
      },
      {
        "name": "flipper_length_mm",
        "type": "number"
      },
      {
        "name": "body_mass_g",
        "type": "number"
      },
      {
        "name": "sex",
        "type": "string"
      },
      {
        "name": "year",
        "type": "integer"
      }
    ],
    "primaryKey": [
      "index"
    ],
    "pandas_version": "1.4.0"
  },
  "data": [
    {
      "index": 0,
      "species": "Adelie",
      "island": "Torgersen",
      "bill_length_mm": 39.1,
      "bill_depth_mm": 18.7,
      "flipper_length_mm": 181.0,
      "body_mass_g": 3750.0,
      "sex": "male",
      "year": 2007
    },
    {
      "index": 1,
      "species": "Adelie",
      "island": "Torgersen",
      "bill_length_mm": 39.5,
      "bill_depth_mm": 17.4,
      "flipper_length_mm": 186.0,
      "body_mass_g": 3800.0,
      "sex": "female",
      "year": 2007
    },
    {
      "index": 2,
      "species": "Adelie",
      "island": "Torgersen",
      "bill_length_mm": 40.3,
      "bill_depth_mm": 18.0,
      "flipper_length_mm": 195.0,
      "body_mass_g": 3250.0,
      "sex": "female",
      "year": 2007
    },
    {
      "index": 3,
      "species": "Adelie",
      "island": "Torgersen",
      "bill_length_mm": null,
      "bill_depth_mm": null,
      "flipper_length_mm": null,
      "body_mass_g": null,
      "sex": null,
      "year": 2007
    },
    {
      "index": 4,
      "species": "Adelie",
      "island": "Torgersen",
      "bill_length_mm": 36.7,
      "bill_depth_mm": 19.3,
      "flipper_length_mm": 193.0,
      "body_mass_g": 3450.0,
      "sex": "female",
      "year": 2007
    }
  ]
}
```

**Comment by rgbkrk** [comment]
Closing as the issue in Deno got fixed in https://github.com/denoland/deno/pull/21272

Upgrade to Deno 1.38.5 or later for the fix!
