### ISSUE TITLE
Polar Data Frames nb: Deno.readCSV tab separator fail

### ISSUE THREAD

**Issue by gplanansky** [rgbkrk/denotebooks#3]
in 10.2_Polar DataFrames.ipynb, ` Deno.readCSV(data, { sep: "\t"}) `  does not separate the column entries:

![rgbkrk-polar-data-frames_readCSCV](https://github.com/rgbkrk/denotebooks/assets/15004741/77e8d548-dc21-4930-88e3-4a9051d902eb)

Seems to be a polars issue.  Is it passing your tests?

**Workaround:**

download the 110m.tsv file and make it a csv file: ` sed -e 's/\t/,/g' 110m.tsv > 110.csv` .

Then it works ok with a comma separator: 

```
let data = await Deno.readTextFile('110m.csv');
let df = pl.readCSV(data, { sep: "," });
```

**platform:**
deno 1.39.3 (release, aarch64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
mac os  / m1 

$ jupyter-lab --version
4.0.10

**Comment by rgbkrk** [comment]
Fixed. Thanks for reporting on it.
